title: Top 5 emoji's
hero_image: images/banner.png
description: Maak een top 5 emoji-webpagina.
meta_title: CSS-animaties | Leer webontwikkeling | Top emoji's
meta_description: Leer webontwikkeling voor beginners met de Raspberry Pi Foundation. Gebruik CSS-animaties om een top 5 emoji's te maken en je website aantrekkelijk te maken.
version: 4
listed: true
copyedit: true
last_tested: "2022-05-11"
steps:
  - 
    title: Inleiding
  - 
    title: Maak een top 5-lijst
  - 
    title: Voeg animatie toe aan een emoji
    completion: engaged
  - 
    title: Voeg een achtergrondafbeelding toe
  - 
    title: Voeg een quote en een link toe
  - 
    title: Voeg animatie toe aan meer emoji's
    completion: internal
  - 
    title: Reflectie
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
