title: Top 5 Emojis
hero_image: images/banner.png
description: Create a top 5 emojis webpage
version: 4
listed: false
copyedit: false
last_tested: "2022-05-11"
steps:
  - title: Introduction
  - title: Create a top 5 list
  - title: Animate an emoji
    completion: engaged
  - title: Add a background image
  - title: Add a quote and a link
  - title: Animate more emojis
    completion: internal
  - title: Reflection
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
