title: Top 5 emojis
hero_image: images/banner.png
description: Create a top 5 emojis webpage.
meta_title: CSS animations | Learn web development | Top emojis
meta_description: Learn web development for beginners with the Raspberry Pi Foundation. Use CSS animations to create a top 5 list of emojis and make your website engaging.
version: 4
listed: true
copyedit: true
last_tested: "2022-05-11"
steps:
  - title: Introduction
  - title: Create a top 5 list
  - title: Animate an emoji
    completion: engaged
  - title: Add a background image
  - title: Add a quote and a link
  - title: Animate more emojis
    completion: internal
  - title: Reflection
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project