title: Top 5 emoji list
hero_image: images/banner.png
description: top-5-emoji-list description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-18"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
