name: 'Top 5 Emoji List'
identifier: 'top-5-emoji-list-step-4'
type: 'html'
components:
  - name: 'index'
    extension: 'html'
    location: 'index.html'
    index: 0
    default: true
  - name: 'style'
    extension: 'css'
    location: style.css
    index: 1
    default: false
  - name: 'animation'
    extension: 'css'
    location: animation.css
    index: 2
    default: false
  - name: 'default'
    extension: 'css'
    location: default.css
    index: 3
    default: false
image:
    - "emojis.png"